# Copyright (c) 2021-2022-2023 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT

name: VoukoderDLL-Build
on:
  push:
  workflow_dispatch:

jobs:
  windows-latest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Restore from cache and setup vcpkg executable and data files.
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Run CMake+vcpkg+Ninja to build packages and generate/build/test the code.
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/VoukoderPro/CMakeLists.txt"
          configurePreset: 'ninja-multiconfiguration-vcpkg'
          buildPreset: 'ninja-multiconfiguration-vcpkg'
          buildPresetAdditionalArgs: "[`--config`, `Release`]"

      - run: dir "${{ github.workspace }}/VoukoderPro/builds/ninja-multiconfiguration-vcpkg/Release/"

      - uses: actions/upload-artifact@v4
        with:
          name: VoukoderDesigner-Windows
          path: "${{ github.workspace }}/VoukoderPro/builds/ninja-multiconfiguration-vcpkg/Release/VoukoderDesigner.exe"

  ubuntu-latest:
    runs-on: ubuntu-latest
    container: ubuntu:noble
    steps:
      - name: Update
        run: apt update

      - name: Upgrade
        run: apt upgrade -y

      - name: Install Deps
        run: apt-get install -y cmake ninja-build build-essential git libboost-all-dev pkg-config ffmpeg libavfilter-dev

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Generate project files
        run: |
          cmake --preset linux-ci "$GITHUB_WORKSPACE/VoukoderPro/"

      - name: Build (Release configuration)
        run: |
          cmake --build --preset linux-ci --config Release
        working-directory: "/__w/VoukoderPro/VoukoderPro/VoukoderPro/"

      - run: ls "/__w/VoukoderPro/VoukoderPro/VoukoderPro/builds/linux-ci/Release/"

      - uses: actions/upload-artifact@v4
        with:
          name: VoukoderDLL-Linux
          path: "/__w/VoukoderPro/VoukoderPro/VoukoderPro/builds/linux-ci/Release/voukoderpro.so"